# Generated by Django 5.1.1 on 2024-10-07 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ksiazka',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ksiazki', to='biblioteka.autor'),
        ),
    ]
