# Generated by Django 5.1.1 on 2024-10-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0002_alter_ksiazka_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='ksiazka',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Nieznany'), (1, 'Fantasy'), (2, 'Horror'), (3, 'Drama')], default=0),
        ),
    ]
